<a href="https://colab.research.google.com/github/AnveshAnnepaga/AI_DS/blob/main/Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
d=np.array([[2,3],[4,5],[6,7],[8,9]])
c=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)
print(d.ndim)
print(c.ndim)

0
1
2
2


In [ ]:
import numpy as np
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
one = np.ones((3,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
random_arr = np.random.random((2,3))
print(random_arr)

[[0.7616505  0.75327484 0.0229897 ]
 [0.79182102 0.4214979  0.08135901]]


In [ ]:
import numpy as np
iden = np.eye((4))
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("shape:",a.shape)
print("size:",a.size)
print("data type:",a.dtype)
print("no.of dimensions:",a.ndim)

shape: (2, 3)
size: 6
data type: int64
no.of dimensions: 2


In [ ]:
import numpy as np

temp_data = np.array([[22, 25, 20],
                      [24, 26, 23]])
print(temp_data)

print("shape:", temp_data.shape)
print("size:", temp_data.size)
print("data type:", temp_data.dtype)
print("dimensions:", temp_data.ndim)

g3 = np.array([[21, 23, 22]])
updated_temp_data = np.vstack((temp_data, g3))

sensor_error_flags = np.zeros((2, 3))
greenhouse_identity = np.identity(3)

print(updated_temp_data)
print(sensor_error_flags)
print(greenhouse_identity)


[[22 25 20]
 [24 26 23]]
shape: (2, 3)
size: 6
data type: int64
dimensions: 2
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,-1])
print(arr[1:])
print(arr[:1])
print(arr[1:,1:])

20
60
[[40 50 60]]
[[10 20 30]]
[[50 60]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.

In [ ]:
import numpy as np

shipments = np.array([[50, 60, 55, 70, 65, 80, 90],
                      [40, 45, 50, 60, 55, 70, 75]])

print("apples on wed", shipments[0, 2])
print("oranges on sunday:",shipments[1, 6])

print("mod-fri:",shipments[0:, 0:5])
print("sat and sun:",shipments[0:, 5:])
print("wed to sat(apple)", shipments[0, 2:6])

shipments[0, 5] = 100
print(shipments)


apples on wed 55
oranges on sunday: 75
mod-fri: [[50 60 55 70 65]
 [40 45 50 60 55]]
sat and sun: [[80 90]
 [70 75]]
wed to sat(apple) [55 70 65 80]
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
import numpy as np

a = np.array([[1,2,3],
              [3,5,8],
              [7,9,10]])

b = np.array([[4,5,6],
              [3,6,8],
              [8,11,2]])

print(a + b)
print(a * b)
print(a * 2)
print(np.dot(a, b))


[[ 5  7  9]
 [ 6 11 16]
 [15 20 12]]
[[ 4 10 18]
 [ 9 30 64]
 [56 99 20]]
[[ 2  4  6]
 [ 6 10 16]
 [14 18 20]]
[[ 34  50  28]
 [ 91 133  74]
 [135 199 134]]


In [ ]:
# BroadCasting
# Numpy automatically applies operations across arrays of different shapes when compatible
a=np.array([1,2,3])
b = 2
print(a+b)

[3 4 5]


In [ ]:
# universal functions(ufuncs)
arr = np.array([1,2,3])

print(np.exp(arr))  #exponent
print(np.sqrt(arr))
print(np.log)

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]



# 1. Arithmetic ufuncs (element-wise operations)
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)

# 2. Exponential and Logarithmic ufuncs
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1

# 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)

# 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)

# 5. Statistical ufuncs (operate along axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)

# 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)

# 7. Comparison ufuncs (return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)

# 8. Bitwise ufuncs (operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)


In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

b = np.array([10, 20, 30, 40])
print(np.mean(b))

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.add(x, y))

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(np.dot(m1, m2))

a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a, b))

print(np.greater(y,x))
print(np.invert(x))

[1 2 3 4]
25.0
[5 7 9]
[[19 22]
 [43 50]]
[False False  True]
[ True  True  True]
[-2 -3 -4]


In [ ]:
farmA = np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB = np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC = np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all = np.array([farmA, farmB, farmC])

print(production_all)
print("shape:", production_all.shape)
print("size :", production_all.size)
print("data type:", production_all.dtype)
print("dimensions:", production_all.ndim)

total_per_farm = np.sum(production_all, axis=(1,2))
mean_per_farm = np.mean(production_all, axis=(1,2))
std_per_farm = np.std(production_all, axis=(1,2))
var_per_farm = np.var(production_all, axis=(1,2))

print(total_per_farm)
print(mean_per_farm)
print(std_per_farm)
print(var_per_farm)

hour_weights = np.array([0.5, 1.0, 0.75])
print("weighted_per_panel:", np.dot(production_all, hour_weights))

production_all[1] = production_all[1] + 0.5

normalized = (production_all - mean_per_farm[:, None, None]) / std_per_farm[:, None, None]

exp_vals = np.exp(normalized)
expm1_vals = np.expm1(normalized)
log_vals = np.log(normalized - np.min(normalized) + 1e-5)
log10_vals = np.log10(normalized - np.min(normalized) + 1e-5)
log2_vals = np.log2(normalized - np.min(normalized) + 1e-5)

sin_vals = np.sin(normalized)
cos_vals = np.cos(normalized)
tan_vals = np.tan(normalized)
arcsin_vals = np.arcsin(np.clip(normalized, -1, 1))
arccos_vals = np.arccos(np.clip(normalized, -1, 1))
arctan_vals = np.arctan(normalized)
degrees_vals = np.degrees(normalized)
radians_vals = np.radians(normalized)

round_vals = np.round(normalized)
floor_vals = np.floor(normalized)
ceil_vals = np.ceil(normalized)
trunc_vals = np.trunc(normalized)

high_output = production_all > 20
even_hours_mask = (np.arange(3) % 2 == 0)
logical_and_vals = np.logical_and(high_output, high_output)
logical_or_vals = np.logical_or(high_output, high_output)
logical_not_vals = np.logical_not(high_output)
logical_xor_vals = np.logical_xor(high_output, high_output)
greater_equal_vals = np.greater_equal(production_all, 15)
less_vals = np.less(production_all, 10)

alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
bitwise_and_vals = np.bitwise_and(alerts, alerts)
bitwise_or_vals = np.bitwise_or(alerts, alerts)
bitwise_invert_vals = np.invert(alerts)

add_vals = np.add(normalized, 1)
sub_vals = np.subtract(normalized, 1)
mul_vals = np.multiply(normalized, 2)
div_vals = np.divide(normalized, 2)
power_vals = np.power(normalized, 2)
mod_vals = np.mod(normalized, 2)

sum_exp = np.sum(np.exp(normalized))
mean_sin = np.mean(np.sin(normalized))

panel_totals_per_farm = np.sum(production_all, axis=2)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)

overall_total = np.sum(production_all)
peak_hour_value = np.max(production_all)
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=2)

print("Total per farm:", total_per_farm)
print("Mean per farm:", mean_per_farm)
print("Std per farm:", std_per_farm)
print("Panel totals per farm:\n", panel_totals_per_farm)
print("Needs maintenance:", needs_maintenance)
print("Overall total:", overall_total)
print("Peak value:", peak_hour_value, "at farm, panel, hour:", peak_idx)
print("Average per panel:\n", average_per_panel)


[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
shape: (3, 4, 3)
size : 36
data type: int64
dimensions: 3
[126 234 174]
[10.5 19.5 14.5]
[1.97905701 1.97905701 1.97905701]
[3.91666667 3.91666667 3.91666667]
weighted_per_panel: [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
Total per farm: [126 234 174]
Mean per farm: [10.5 19.5 14.5]
Std per farm: [1.97905701 1.97905701 1.97905701]
Panel totals per farm:
 [[33 30 39 24]
 [60 57 66 51]
 [45 42 51 36]]
Needs maintenance: [ True False  True]
Overall total: 534
Peak value: 23 at farm, panel, hour: (np.int64(1), np.int64(2), np.int64(1))
Average per panel:
 [[11. 10. 13.  8.]
 [20. 19. 22. 17.]
 [15. 14. 17. 12.]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr)
resh = arr.reshape(3,2)
print(resh)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# stacking and splitting
# a.Stacking
a=np.array([1,2])
b=np.array([3,4])

# vertical stack
print(np.vstack((a,b)))
# horizontal stack
print(np.hstack((a,b)))

# b.Splitting
arr = np.array([1,2,3,4,5,6])
# split into 3 parts
print(np.array_split(arr,3))


[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1,2,3])
np.save('array1.npy',arr)

loaded_arr = np.load('array.npy')
print(loaded_arr)

copy=arr.copy()
copy[0]=10
print(arr)

[1 2 3]
[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [ ]:
import numpy as np

arr1 = np.arange(10, 51)
arr2 = np.random.rand(3, 3)

print("arr1:", arr1)
print("arr2:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)

arr = np.array([1, 2, 3, 4, 5])
arr_add = arr + 5
print("After adding 5:", arr_add)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = a * b
print("Element-wise multiplication:\n", result)

arr3 = np.arange(1, 26).reshape(5, 5)
first_row = arr3[0]
last_col = arr3[:, -1]
subarray = arr3[:3, :2]

print("First row:", first_row)
print("Last column:", last_col)
print("Subarray (first 3 rows, first 2 cols):\n", subarray)


arr4 = np.random.randint(10, 101, 10)
print("Array:", arr4)
print("Max:", arr4.max())
print("Min:", arr4.min())
print("Mean:", arr4.mean())
print("Standard Deviation:", arr4.std())

arr5=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr6=arr5.reshape(3,4)
print("arr6:\n",arr6)

arr7=np.ones((3,3))
print("arr7",arr7)
arr8=np.array([1,2,3])
arr9=arr7+arr8
print("arr9:\n",arr9)


arr10 = np.random.randint(1, 51,20)
div_by_5 = arr10[arr10 % 5 == 0]
print("Array:", arr10)
print("Elements divisible by 5:", div_by_5)

arr11=np.array([[1,2],[3,4]])
arr12=np.array([[5,6],[7,8]])
result=np.dot(arr11,arr12)
print("result:\n",result)

arr13 = np.arange(1, 17).reshape(4, 4)
diag_elements = arr13[np.arange(4), np.arange(4)]
print("Array:\n", arr13)
print("Diagonal elements:", diag_elements)

arr1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
arr2:
 [[0.19513331 0.56592456 0.08572145]
 [0.00682398 0.58769839 0.0929428 ]
 [0.61800066 0.85998759 0.21654813]]
Shape: (3, 3)
Size: 9
Data type: float64
After adding 5: [ 6  7  8  9 10]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray (first 3 rows, first 2 cols):
 [[ 1  2]
 [ 6  7]
 [11 12]]
Array: [94 91 99 81 50 79 89 14 52 53]
Max: 99
Min: 14
Mean: 70.2
Standard Deviation: 25.63123094976127
arr6:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr7 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr9:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
Array: [ 2  3 50 48 41 26 14 17 45 31 10 22 46  9 28 24 27 15  7  5]
Elements divisible by 5: [50 45 10 15  5]
result:
 [[19 22]
 [43 50]]
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]
